FROM mirror.gcr.io/python:3.12-slim

WORKDIR /home

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt update
RUN apt -y install netcat-traditional mariadb-client build-essential

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install "taskiq[reload]==0.11.5"

ENTRYPOINT ["/home/entrypoint.app.dev.sh"]
